#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db3")]
	public partial class DataClasses2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertenteghadatvapishnahadha(enteghadatvapishnahadha instance);
    partial void Updateenteghadatvapishnahadha(enteghadatvapishnahadha instance);
    partial void Deleteenteghadatvapishnahadha(enteghadatvapishnahadha instance);
    partial void Insertjhanr(jhanr instance);
    partial void Updatejhanr(jhanr instance);
    partial void Deletejhanr(jhanr instance);
    partial void Insertliked(liked instance);
    partial void Updateliked(liked instance);
    partial void Deleteliked(liked instance);
    partial void Insertpishnahad(pishnahad instance);
    partial void Updatepishnahad(pishnahad instance);
    partial void Deletepishnahad(pishnahad instance);
    partial void Insertshenideshode(shenideshode instance);
    partial void Updateshenideshode(shenideshode instance);
    partial void Deleteshenideshode(shenideshode instance);
    partial void Inserttablighat(tablighat instance);
    partial void Updatetablighat(tablighat instance);
    partial void Deletetablighat(tablighat instance);
    partial void Insertmusic(music instance);
    partial void Updatemusic(music instance);
    partial void Deletemusic(music instance);
    partial void Insertsuggestion(suggestion instance);
    partial void Updatesuggestion(suggestion instance);
    partial void Deletesuggestion(suggestion instance);
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    #endregion
		
		public DataClasses2DataContext() : 
				base(global::WindowsFormsApplication1.Properties.Settings.Default.db3ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<enteghadatvapishnahadha> enteghadatvapishnahadhas
		{
			get
			{
				return this.GetTable<enteghadatvapishnahadha>();
			}
		}
		
		public System.Data.Linq.Table<jhanr> jhanrs
		{
			get
			{
				return this.GetTable<jhanr>();
			}
		}
		
		public System.Data.Linq.Table<liked> likeds
		{
			get
			{
				return this.GetTable<liked>();
			}
		}
		
		public System.Data.Linq.Table<pishnahad> pishnahads
		{
			get
			{
				return this.GetTable<pishnahad>();
			}
		}
		
		public System.Data.Linq.Table<shenideshode> shenideshodes
		{
			get
			{
				return this.GetTable<shenideshode>();
			}
		}
		
		public System.Data.Linq.Table<tablighat> tablighats
		{
			get
			{
				return this.GetTable<tablighat>();
			}
		}
		
		public System.Data.Linq.Table<music> musics
		{
			get
			{
				return this.GetTable<music>();
			}
		}
		
		public System.Data.Linq.Table<suggestion> suggestions
		{
			get
			{
				return this.GetTable<suggestion>();
			}
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<t2> t2s
		{
			get
			{
				return this.GetTable<t2>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.enteghadatvapishnahadha")]
	public partial class enteghadatvapishnahadha : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _musicid;
		
		private System.Nullable<int> _userid;
		
		private string _matn;
		
		private EntityRef<music> _music;
		
		private EntityRef<user> _user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmusicidChanging(System.Nullable<int> value);
    partial void OnmusicidChanged();
    partial void OnuseridChanging(System.Nullable<int> value);
    partial void OnuseridChanged();
    partial void OnmatnChanging(string value);
    partial void OnmatnChanged();
    #endregion
		
		public enteghadatvapishnahadha()
		{
			this._music = default(EntityRef<music>);
			this._user = default(EntityRef<user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_musicid", DbType="Int")]
		public System.Nullable<int> musicid
		{
			get
			{
				return this._musicid;
			}
			set
			{
				if ((this._musicid != value))
				{
					if (this._music.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmusicidChanging(value);
					this.SendPropertyChanging();
					this._musicid = value;
					this.SendPropertyChanged("musicid");
					this.OnmusicidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
		public System.Nullable<int> userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					if (this._user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matn", DbType="VarChar(200)")]
		public string matn
		{
			get
			{
				return this._matn;
			}
			set
			{
				if ((this._matn != value))
				{
					this.OnmatnChanging(value);
					this.SendPropertyChanging();
					this._matn = value;
					this.SendPropertyChanged("matn");
					this.OnmatnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="music_enteghadatvapishnahadha", Storage="_music", ThisKey="musicid", OtherKey="id", IsForeignKey=true)]
		public music music
		{
			get
			{
				return this._music.Entity;
			}
			set
			{
				music previousValue = this._music.Entity;
				if (((previousValue != value) 
							|| (this._music.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._music.Entity = null;
						previousValue.enteghadatvapishnahadhas.Remove(this);
					}
					this._music.Entity = value;
					if ((value != null))
					{
						value.enteghadatvapishnahadhas.Add(this);
						this._musicid = value.id;
					}
					else
					{
						this._musicid = default(Nullable<int>);
					}
					this.SendPropertyChanged("music");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_enteghadatvapishnahadha", Storage="_user", ThisKey="userid", OtherKey="id", IsForeignKey=true)]
		public user user
		{
			get
			{
				return this._user.Entity;
			}
			set
			{
				user previousValue = this._user.Entity;
				if (((previousValue != value) 
							|| (this._user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user.Entity = null;
						previousValue.enteghadatvapishnahadhas.Remove(this);
					}
					this._user.Entity = value;
					if ((value != null))
					{
						value.enteghadatvapishnahadhas.Add(this);
						this._userid = value.id;
					}
					else
					{
						this._userid = default(Nullable<int>);
					}
					this.SendPropertyChanged("user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jhanr")]
	public partial class jhanr : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private EntitySet<tablighat> _tablighats;
		
		private EntitySet<music> _musics;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public jhanr()
		{
			this._tablighats = new EntitySet<tablighat>(new Action<tablighat>(this.attach_tablighats), new Action<tablighat>(this.detach_tablighats));
			this._musics = new EntitySet<music>(new Action<music>(this.attach_musics), new Action<music>(this.detach_musics));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(30)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="jhanr_tablighat", Storage="_tablighats", ThisKey="id", OtherKey="jhanrid")]
		public EntitySet<tablighat> tablighats
		{
			get
			{
				return this._tablighats;
			}
			set
			{
				this._tablighats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="jhanr_music", Storage="_musics", ThisKey="id", OtherKey="jhanrid")]
		public EntitySet<music> musics
		{
			get
			{
				return this._musics;
			}
			set
			{
				this._musics.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tablighats(tablighat entity)
		{
			this.SendPropertyChanging();
			entity.jhanr = this;
		}
		
		private void detach_tablighats(tablighat entity)
		{
			this.SendPropertyChanging();
			entity.jhanr = null;
		}
		
		private void attach_musics(music entity)
		{
			this.SendPropertyChanging();
			entity.jhanr = this;
		}
		
		private void detach_musics(music entity)
		{
			this.SendPropertyChanging();
			entity.jhanr = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.liked")]
	public partial class liked : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _musicid;
		
		private System.Nullable<int> _userid;
		
		private EntityRef<music> _music;
		
		private EntityRef<user> _user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmusicidChanging(System.Nullable<int> value);
    partial void OnmusicidChanged();
    partial void OnuseridChanging(System.Nullable<int> value);
    partial void OnuseridChanged();
    #endregion
		
		public liked()
		{
			this._music = default(EntityRef<music>);
			this._user = default(EntityRef<user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_musicid", DbType="Int")]
		public System.Nullable<int> musicid
		{
			get
			{
				return this._musicid;
			}
			set
			{
				if ((this._musicid != value))
				{
					if (this._music.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmusicidChanging(value);
					this.SendPropertyChanging();
					this._musicid = value;
					this.SendPropertyChanged("musicid");
					this.OnmusicidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
		public System.Nullable<int> userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					if (this._user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="music_liked", Storage="_music", ThisKey="musicid", OtherKey="id", IsForeignKey=true)]
		public music music
		{
			get
			{
				return this._music.Entity;
			}
			set
			{
				music previousValue = this._music.Entity;
				if (((previousValue != value) 
							|| (this._music.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._music.Entity = null;
						previousValue.likeds.Remove(this);
					}
					this._music.Entity = value;
					if ((value != null))
					{
						value.likeds.Add(this);
						this._musicid = value.id;
					}
					else
					{
						this._musicid = default(Nullable<int>);
					}
					this.SendPropertyChanged("music");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_liked", Storage="_user", ThisKey="userid", OtherKey="id", IsForeignKey=true)]
		public user user
		{
			get
			{
				return this._user.Entity;
			}
			set
			{
				user previousValue = this._user.Entity;
				if (((previousValue != value) 
							|| (this._user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user.Entity = null;
						previousValue.likeds.Remove(this);
					}
					this._user.Entity = value;
					if ((value != null))
					{
						value.likeds.Add(this);
						this._userid = value.id;
					}
					else
					{
						this._userid = default(Nullable<int>);
					}
					this.SendPropertyChanged("user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pishnahad")]
	public partial class pishnahad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name_new_music_pishnahadi;
		
		private System.Nullable<int> _userid;
		
		private EntityRef<user> _user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onname_new_music_pishnahadiChanging(string value);
    partial void Onname_new_music_pishnahadiChanged();
    partial void OnuseridChanging(System.Nullable<int> value);
    partial void OnuseridChanged();
    #endregion
		
		public pishnahad()
		{
			this._user = default(EntityRef<user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_new_music_pishnahadi", DbType="VarChar(30)")]
		public string name_new_music_pishnahadi
		{
			get
			{
				return this._name_new_music_pishnahadi;
			}
			set
			{
				if ((this._name_new_music_pishnahadi != value))
				{
					this.Onname_new_music_pishnahadiChanging(value);
					this.SendPropertyChanging();
					this._name_new_music_pishnahadi = value;
					this.SendPropertyChanged("name_new_music_pishnahadi");
					this.Onname_new_music_pishnahadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
		public System.Nullable<int> userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					if (this._user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_pishnahad", Storage="_user", ThisKey="userid", OtherKey="id", IsForeignKey=true)]
		public user user
		{
			get
			{
				return this._user.Entity;
			}
			set
			{
				user previousValue = this._user.Entity;
				if (((previousValue != value) 
							|| (this._user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user.Entity = null;
						previousValue.pishnahads.Remove(this);
					}
					this._user.Entity = value;
					if ((value != null))
					{
						value.pishnahads.Add(this);
						this._userid = value.id;
					}
					else
					{
						this._userid = default(Nullable<int>);
					}
					this.SendPropertyChanged("user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.shenideshode")]
	public partial class shenideshode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _musicid;
		
		private System.Nullable<int> _userid;
		
		private EntityRef<music> _music;
		
		private EntityRef<user> _user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmusicidChanging(System.Nullable<int> value);
    partial void OnmusicidChanged();
    partial void OnuseridChanging(System.Nullable<int> value);
    partial void OnuseridChanged();
    #endregion
		
		public shenideshode()
		{
			this._music = default(EntityRef<music>);
			this._user = default(EntityRef<user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_musicid", DbType="Int")]
		public System.Nullable<int> musicid
		{
			get
			{
				return this._musicid;
			}
			set
			{
				if ((this._musicid != value))
				{
					if (this._music.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmusicidChanging(value);
					this.SendPropertyChanging();
					this._musicid = value;
					this.SendPropertyChanged("musicid");
					this.OnmusicidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
		public System.Nullable<int> userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					if (this._user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="music_shenideshode", Storage="_music", ThisKey="musicid", OtherKey="id", IsForeignKey=true)]
		public music music
		{
			get
			{
				return this._music.Entity;
			}
			set
			{
				music previousValue = this._music.Entity;
				if (((previousValue != value) 
							|| (this._music.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._music.Entity = null;
						previousValue.shenideshodes.Remove(this);
					}
					this._music.Entity = value;
					if ((value != null))
					{
						value.shenideshodes.Add(this);
						this._musicid = value.id;
					}
					else
					{
						this._musicid = default(Nullable<int>);
					}
					this.SendPropertyChanged("music");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_shenideshode", Storage="_user", ThisKey="userid", OtherKey="id", IsForeignKey=true)]
		public user user
		{
			get
			{
				return this._user.Entity;
			}
			set
			{
				user previousValue = this._user.Entity;
				if (((previousValue != value) 
							|| (this._user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user.Entity = null;
						previousValue.shenideshodes.Remove(this);
					}
					this._user.Entity = value;
					if ((value != null))
					{
						value.shenideshodes.Add(this);
						this._userid = value.id;
					}
					else
					{
						this._userid = default(Nullable<int>);
					}
					this.SendPropertyChanged("user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tablighat")]
	public partial class tablighat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _ahamiyat;
		
		private System.Nullable<System.DateTime> _akharin_zamane_nemayesh;
		
		private string _adresefile;
		
		private System.Nullable<int> _jhanrid;
		
		private EntityRef<jhanr> _jhanr;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnahamiyatChanging(System.Nullable<int> value);
    partial void OnahamiyatChanged();
    partial void Onakharin_zamane_nemayeshChanging(System.Nullable<System.DateTime> value);
    partial void Onakharin_zamane_nemayeshChanged();
    partial void OnadresefileChanging(string value);
    partial void OnadresefileChanged();
    partial void OnjhanridChanging(System.Nullable<int> value);
    partial void OnjhanridChanged();
    #endregion
		
		public tablighat()
		{
			this._jhanr = default(EntityRef<jhanr>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ahamiyat", DbType="Int")]
		public System.Nullable<int> ahamiyat
		{
			get
			{
				return this._ahamiyat;
			}
			set
			{
				if ((this._ahamiyat != value))
				{
					this.OnahamiyatChanging(value);
					this.SendPropertyChanging();
					this._ahamiyat = value;
					this.SendPropertyChanged("ahamiyat");
					this.OnahamiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_akharin_zamane_nemayesh", DbType="Date")]
		public System.Nullable<System.DateTime> akharin_zamane_nemayesh
		{
			get
			{
				return this._akharin_zamane_nemayesh;
			}
			set
			{
				if ((this._akharin_zamane_nemayesh != value))
				{
					this.Onakharin_zamane_nemayeshChanging(value);
					this.SendPropertyChanging();
					this._akharin_zamane_nemayesh = value;
					this.SendPropertyChanged("akharin_zamane_nemayesh");
					this.Onakharin_zamane_nemayeshChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresefile", DbType="VarChar(100)")]
		public string adresefile
		{
			get
			{
				return this._adresefile;
			}
			set
			{
				if ((this._adresefile != value))
				{
					this.OnadresefileChanging(value);
					this.SendPropertyChanging();
					this._adresefile = value;
					this.SendPropertyChanged("adresefile");
					this.OnadresefileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jhanrid", DbType="Int")]
		public System.Nullable<int> jhanrid
		{
			get
			{
				return this._jhanrid;
			}
			set
			{
				if ((this._jhanrid != value))
				{
					if (this._jhanr.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnjhanridChanging(value);
					this.SendPropertyChanging();
					this._jhanrid = value;
					this.SendPropertyChanged("jhanrid");
					this.OnjhanridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="jhanr_tablighat", Storage="_jhanr", ThisKey="jhanrid", OtherKey="id", IsForeignKey=true)]
		public jhanr jhanr
		{
			get
			{
				return this._jhanr.Entity;
			}
			set
			{
				jhanr previousValue = this._jhanr.Entity;
				if (((previousValue != value) 
							|| (this._jhanr.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._jhanr.Entity = null;
						previousValue.tablighats.Remove(this);
					}
					this._jhanr.Entity = value;
					if ((value != null))
					{
						value.tablighats.Add(this);
						this._jhanrid = value.id;
					}
					else
					{
						this._jhanrid = default(Nullable<int>);
					}
					this.SendPropertyChanged("jhanr");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.music")]
	public partial class music : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _fileaddress;
		
		private System.Nullable<int> _jhanrid;
		
		private EntitySet<enteghadatvapishnahadha> _enteghadatvapishnahadhas;
		
		private EntitySet<liked> _likeds;
		
		private EntitySet<shenideshode> _shenideshodes;
		
		private EntitySet<suggestion> _suggestions;
		
		private EntityRef<jhanr> _jhanr;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnfileaddressChanging(string value);
    partial void OnfileaddressChanged();
    partial void OnjhanridChanging(System.Nullable<int> value);
    partial void OnjhanridChanged();
    #endregion
		
		public music()
		{
			this._enteghadatvapishnahadhas = new EntitySet<enteghadatvapishnahadha>(new Action<enteghadatvapishnahadha>(this.attach_enteghadatvapishnahadhas), new Action<enteghadatvapishnahadha>(this.detach_enteghadatvapishnahadhas));
			this._likeds = new EntitySet<liked>(new Action<liked>(this.attach_likeds), new Action<liked>(this.detach_likeds));
			this._shenideshodes = new EntitySet<shenideshode>(new Action<shenideshode>(this.attach_shenideshodes), new Action<shenideshode>(this.detach_shenideshodes));
			this._suggestions = new EntitySet<suggestion>(new Action<suggestion>(this.attach_suggestions), new Action<suggestion>(this.detach_suggestions));
			this._jhanr = default(EntityRef<jhanr>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(30)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fileaddress", DbType="VarChar(100)")]
		public string fileaddress
		{
			get
			{
				return this._fileaddress;
			}
			set
			{
				if ((this._fileaddress != value))
				{
					this.OnfileaddressChanging(value);
					this.SendPropertyChanging();
					this._fileaddress = value;
					this.SendPropertyChanged("fileaddress");
					this.OnfileaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jhanrid", DbType="Int")]
		public System.Nullable<int> jhanrid
		{
			get
			{
				return this._jhanrid;
			}
			set
			{
				if ((this._jhanrid != value))
				{
					if (this._jhanr.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnjhanridChanging(value);
					this.SendPropertyChanging();
					this._jhanrid = value;
					this.SendPropertyChanged("jhanrid");
					this.OnjhanridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="music_enteghadatvapishnahadha", Storage="_enteghadatvapishnahadhas", ThisKey="id", OtherKey="musicid")]
		public EntitySet<enteghadatvapishnahadha> enteghadatvapishnahadhas
		{
			get
			{
				return this._enteghadatvapishnahadhas;
			}
			set
			{
				this._enteghadatvapishnahadhas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="music_liked", Storage="_likeds", ThisKey="id", OtherKey="musicid")]
		public EntitySet<liked> likeds
		{
			get
			{
				return this._likeds;
			}
			set
			{
				this._likeds.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="music_shenideshode", Storage="_shenideshodes", ThisKey="id", OtherKey="musicid")]
		public EntitySet<shenideshode> shenideshodes
		{
			get
			{
				return this._shenideshodes;
			}
			set
			{
				this._shenideshodes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="music_suggestion", Storage="_suggestions", ThisKey="id", OtherKey="musicid")]
		public EntitySet<suggestion> suggestions
		{
			get
			{
				return this._suggestions;
			}
			set
			{
				this._suggestions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="jhanr_music", Storage="_jhanr", ThisKey="jhanrid", OtherKey="id", IsForeignKey=true)]
		public jhanr jhanr
		{
			get
			{
				return this._jhanr.Entity;
			}
			set
			{
				jhanr previousValue = this._jhanr.Entity;
				if (((previousValue != value) 
							|| (this._jhanr.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._jhanr.Entity = null;
						previousValue.musics.Remove(this);
					}
					this._jhanr.Entity = value;
					if ((value != null))
					{
						value.musics.Add(this);
						this._jhanrid = value.id;
					}
					else
					{
						this._jhanrid = default(Nullable<int>);
					}
					this.SendPropertyChanged("jhanr");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_enteghadatvapishnahadhas(enteghadatvapishnahadha entity)
		{
			this.SendPropertyChanging();
			entity.music = this;
		}
		
		private void detach_enteghadatvapishnahadhas(enteghadatvapishnahadha entity)
		{
			this.SendPropertyChanging();
			entity.music = null;
		}
		
		private void attach_likeds(liked entity)
		{
			this.SendPropertyChanging();
			entity.music = this;
		}
		
		private void detach_likeds(liked entity)
		{
			this.SendPropertyChanging();
			entity.music = null;
		}
		
		private void attach_shenideshodes(shenideshode entity)
		{
			this.SendPropertyChanging();
			entity.music = this;
		}
		
		private void detach_shenideshodes(shenideshode entity)
		{
			this.SendPropertyChanging();
			entity.music = null;
		}
		
		private void attach_suggestions(suggestion entity)
		{
			this.SendPropertyChanging();
			entity.music = this;
		}
		
		private void detach_suggestions(suggestion entity)
		{
			this.SendPropertyChanging();
			entity.music = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.suggestion")]
	public partial class suggestion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _musicid;
		
		private System.Nullable<int> _userid;
		
		private EntityRef<music> _music;
		
		private EntityRef<user> _user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmusicidChanging(System.Nullable<int> value);
    partial void OnmusicidChanged();
    partial void OnuseridChanging(System.Nullable<int> value);
    partial void OnuseridChanged();
    #endregion
		
		public suggestion()
		{
			this._music = default(EntityRef<music>);
			this._user = default(EntityRef<user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_musicid", DbType="Int")]
		public System.Nullable<int> musicid
		{
			get
			{
				return this._musicid;
			}
			set
			{
				if ((this._musicid != value))
				{
					if (this._music.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmusicidChanging(value);
					this.SendPropertyChanging();
					this._musicid = value;
					this.SendPropertyChanged("musicid");
					this.OnmusicidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="Int")]
		public System.Nullable<int> userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					if (this._user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="music_suggestion", Storage="_music", ThisKey="musicid", OtherKey="id", IsForeignKey=true)]
		public music music
		{
			get
			{
				return this._music.Entity;
			}
			set
			{
				music previousValue = this._music.Entity;
				if (((previousValue != value) 
							|| (this._music.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._music.Entity = null;
						previousValue.suggestions.Remove(this);
					}
					this._music.Entity = value;
					if ((value != null))
					{
						value.suggestions.Add(this);
						this._musicid = value.id;
					}
					else
					{
						this._musicid = default(Nullable<int>);
					}
					this.SendPropertyChanged("music");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_suggestion", Storage="_user", ThisKey="userid", OtherKey="id", IsForeignKey=true)]
		public user user
		{
			get
			{
				return this._user.Entity;
			}
			set
			{
				user previousValue = this._user.Entity;
				if (((previousValue != value) 
							|| (this._user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user.Entity = null;
						previousValue.suggestions.Remove(this);
					}
					this._user.Entity = value;
					if ((value != null))
					{
						value.suggestions.Add(this);
						this._userid = value.id;
					}
					else
					{
						this._userid = default(Nullable<int>);
					}
					this.SendPropertyChanged("user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _username;
		
		private string _pas;
		
		private System.Nullable<int> _saletavalod;
		
		private string _email;
		
		private string _ismodir;
		
		private EntitySet<enteghadatvapishnahadha> _enteghadatvapishnahadhas;
		
		private EntitySet<liked> _likeds;
		
		private EntitySet<pishnahad> _pishnahads;
		
		private EntitySet<shenideshode> _shenideshodes;
		
		private EntitySet<suggestion> _suggestions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasChanging(string value);
    partial void OnpasChanged();
    partial void OnsaletavalodChanging(System.Nullable<int> value);
    partial void OnsaletavalodChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnismodirChanging(string value);
    partial void OnismodirChanged();
    #endregion
		
		public user()
		{
			this._enteghadatvapishnahadhas = new EntitySet<enteghadatvapishnahadha>(new Action<enteghadatvapishnahadha>(this.attach_enteghadatvapishnahadhas), new Action<enteghadatvapishnahadha>(this.detach_enteghadatvapishnahadhas));
			this._likeds = new EntitySet<liked>(new Action<liked>(this.attach_likeds), new Action<liked>(this.detach_likeds));
			this._pishnahads = new EntitySet<pishnahad>(new Action<pishnahad>(this.attach_pishnahads), new Action<pishnahad>(this.detach_pishnahads));
			this._shenideshodes = new EntitySet<shenideshode>(new Action<shenideshode>(this.attach_shenideshodes), new Action<shenideshode>(this.detach_shenideshodes));
			this._suggestions = new EntitySet<suggestion>(new Action<suggestion>(this.attach_suggestions), new Action<suggestion>(this.detach_suggestions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(30)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(30)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pas", DbType="VarChar(30)")]
		public string pas
		{
			get
			{
				return this._pas;
			}
			set
			{
				if ((this._pas != value))
				{
					this.OnpasChanging(value);
					this.SendPropertyChanging();
					this._pas = value;
					this.SendPropertyChanged("pas");
					this.OnpasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saletavalod", DbType="Int")]
		public System.Nullable<int> saletavalod
		{
			get
			{
				return this._saletavalod;
			}
			set
			{
				if ((this._saletavalod != value))
				{
					this.OnsaletavalodChanging(value);
					this.SendPropertyChanging();
					this._saletavalod = value;
					this.SendPropertyChanged("saletavalod");
					this.OnsaletavalodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ismodir", DbType="NChar(5)")]
		public string ismodir
		{
			get
			{
				return this._ismodir;
			}
			set
			{
				if ((this._ismodir != value))
				{
					this.OnismodirChanging(value);
					this.SendPropertyChanging();
					this._ismodir = value;
					this.SendPropertyChanged("ismodir");
					this.OnismodirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_enteghadatvapishnahadha", Storage="_enteghadatvapishnahadhas", ThisKey="id", OtherKey="userid")]
		public EntitySet<enteghadatvapishnahadha> enteghadatvapishnahadhas
		{
			get
			{
				return this._enteghadatvapishnahadhas;
			}
			set
			{
				this._enteghadatvapishnahadhas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_liked", Storage="_likeds", ThisKey="id", OtherKey="userid")]
		public EntitySet<liked> likeds
		{
			get
			{
				return this._likeds;
			}
			set
			{
				this._likeds.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_pishnahad", Storage="_pishnahads", ThisKey="id", OtherKey="userid")]
		public EntitySet<pishnahad> pishnahads
		{
			get
			{
				return this._pishnahads;
			}
			set
			{
				this._pishnahads.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_shenideshode", Storage="_shenideshodes", ThisKey="id", OtherKey="userid")]
		public EntitySet<shenideshode> shenideshodes
		{
			get
			{
				return this._shenideshodes;
			}
			set
			{
				this._shenideshodes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_suggestion", Storage="_suggestions", ThisKey="id", OtherKey="userid")]
		public EntitySet<suggestion> suggestions
		{
			get
			{
				return this._suggestions;
			}
			set
			{
				this._suggestions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_enteghadatvapishnahadhas(enteghadatvapishnahadha entity)
		{
			this.SendPropertyChanging();
			entity.user = this;
		}
		
		private void detach_enteghadatvapishnahadhas(enteghadatvapishnahadha entity)
		{
			this.SendPropertyChanging();
			entity.user = null;
		}
		
		private void attach_likeds(liked entity)
		{
			this.SendPropertyChanging();
			entity.user = this;
		}
		
		private void detach_likeds(liked entity)
		{
			this.SendPropertyChanging();
			entity.user = null;
		}
		
		private void attach_pishnahads(pishnahad entity)
		{
			this.SendPropertyChanging();
			entity.user = this;
		}
		
		private void detach_pishnahads(pishnahad entity)
		{
			this.SendPropertyChanging();
			entity.user = null;
		}
		
		private void attach_shenideshodes(shenideshode entity)
		{
			this.SendPropertyChanging();
			entity.user = this;
		}
		
		private void detach_shenideshodes(shenideshode entity)
		{
			this.SendPropertyChanging();
			entity.user = null;
		}
		
		private void attach_suggestions(suggestion entity)
		{
			this.SendPropertyChanging();
			entity.user = this;
		}
		
		private void detach_suggestions(suggestion entity)
		{
			this.SendPropertyChanging();
			entity.user = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t2")]
	public partial class t2
	{
		
		private System.Nullable<int> _id;
		
		private System.Nullable<int> _n;
		
		public t2()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_n", DbType="Int")]
		public System.Nullable<int> n
		{
			get
			{
				return this._n;
			}
			set
			{
				if ((this._n != value))
				{
					this._n = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
