<?xml version="1.0" encoding="utf-8"?><Database Name="narm1" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=narm1;Integrated Security=True" SettingsObjectName="WindowsFormsApplication1.Properties.Settings" SettingsPropertyName="narm1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Likes" Member="Likes">
    <Type Name="Like">
      <Column Name="PersonID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MusicID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="PersonID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Likes" Member="Like1s">
    <Type Name="Like1">
      <Column Name="PersonID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MusicID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>